global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "server"
    static_configs:
      - targets: ["docker.for.mac.host.internal:3001"] # da pensare a cosa succede se qualcuno cambia porta alla dashboard
